name: server
version: 0.0.0
license: BSD3
author: "Dor"
category: Web
extra-source-files:
  - README.md

dependencies:
  - base >= 4 && < 5
  - scotty
  - aeson
  - text
  - random
  - wai-middleware-static
  - containers
  - directory

executables:
  server:
    main: Main.hs
    source-dirs: .
    ghc-options:
      - -Wall
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
    extensions:
      - OverloadedStrings