name: server
version: 0.0.0
license: BSD3
author: "Dor"
category: Web

dependencies:
  - base >= 4 && < 5
  - aeson
  - text
  - random
  - wai-middleware-static
  - containers
  - directory
  - servant
  - wai
  - servant-server
  - warp

executables:
  server:
    main: Main.hs
    source-dirs:
      - .
      - routers
      - services
      - middlewares
    other-modules:
      - WordRouter
      - StaticRouter
      - WordService
      - Middleware
    ghc-options:
      - -Wall
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
    extensions:
      - OverloadedStrings